import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { generateIcons } from './icons.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
await generateIcons(root);
const files = ['browser-api.js', 'matcher.js', 'protocol.js', 'storage.js', 'client.js', 'tab-tracker.js', 'meeting-controller.js', 'notifications.js', 'background.js'];
const bundle = '// LocalMeetAssist 1.4.0 — generated by scripts/build.mjs; edit src/, then rebuild.\n' +
  (await Promise.all(files.map(async name => `\n// ---- ${name} ----\n${await readFile(path.join(root, 'src', name), 'utf8')}`))).join('\n');
for (const target of ['chrome', 'firefox']) {
  const out = path.join(root, 'dist', target);
  await rm(out, { recursive: true, force: true });
  await mkdir(out, { recursive: true });
  await writeFile(path.join(out, 'background.js'), bundle);
  for (const name of ['browser-api.js', 'ui.js', 'options.html', 'options.js', 'popup.html', 'popup.js', 'styles.css', 'icons', 'ui-icons']) {
    await cp(path.join(root, 'src', name), path.join(out, name), { recursive: true });
  }
  await cp(path.join(root, 'manifests', `manifest.${target}.json`), path.join(out, 'manifest.json'));
}
console.log('Built dist/chrome and dist/firefox (no dependencies, no minification).');
